/**
 * @file
 * This file contains implementation of
 * com.irurueta.geometry.epipolar.estimators.FundamentalMatrixEstimatorListener
 * 
 * @author Alberto Irurueta (alberto@irurueta.com)
 * @date April 12, 2015
 */
package com.irurueta.geometry.epipolar.estimators;

import com.irurueta.geometry.epipolar.FundamentalMatrix;

/**
 * Listener to be notified of events generated by a non-robust fundamental 
 * matrix estimator.
 */
public interface FundamentalMatrixEstimatorListener {
    
    /**
     * Called when fundamental matrix estimation starts.
     * @param estimator a non-robust fundamental matrix estimator.
     */
    void onEstimateStart(FundamentalMatrixEstimator estimator);
    
    /**
     * Called when fundamental matrix estimation ends.
     * @param estimator a non-robust fundamental matrix estimator.
     * @param fundamentalMatrix estimated fundamental matrix.
     */
    void onEstimateEnd(FundamentalMatrixEstimator estimator, 
            FundamentalMatrix fundamentalMatrix);
}
