/**
 * @file
 * This file contains implementation of
 * com.irurueta.geometry.epipolar.estimators.HomographyDecomposerListener
 * 
 * @author Alberto Irurueta (alberto@irurueta.com)
 * @date May 24, 2017.
 */
package com.irurueta.geometry.epipolar.estimators;

import java.util.List;

/**
 * Listener to be notified of events generated by an homography decomposer.
 */
public interface HomographyDecomposerListener {
    
    /**
     * Called when decomposition starts.
     * @param decomposer an homography decomposer.
     */
    void onDecomposeStart(HomographyDecomposer decomposer);
    
    /**
     * Called when decomposition ends.
     * @param decomposer an homography decomposer.
     * @param result estimated possible homography decompositions.
     */
    void onDecomposeEnd(HomographyDecomposer decomposer, 
            List<HomographyDecomposition> result);
}
