/**
 * @file
 * This file contains implementation of
 * com.irurueta.geometry.epipolar.estimators.PlanarFundamentalMatrixEstimatorListener
 * 
 * @author Alberto Irurueta (alberto@irurueta.com)
 * @date May 20, 2017.
 */
package com.irurueta.geometry.epipolar.estimators;

import com.irurueta.geometry.epipolar.FundamentalMatrix;
import java.util.List;

/**
 * Listener to be notified of events generated by a planar fundamental matrix
 * estimator.
 */
public interface PlanarFundamentalMatrixEstimatorListener {
    
    /**
     * Called when fundamental matrix estimation starts.
     * @param estimator a planar fundamental matrix estimator.
     */
    void onEstimateStart(PlanarFundamentalMatrixEstimator estimator);
    
    /**
     * Called when fundamental matrix estimation ends.
     * @param estimator a planar fundamental matrix estimator.
     * @param fundamentalMatrices estimated fundamental matrices.
     */
    void onEstimateEnd(PlanarFundamentalMatrixEstimator estimator, 
            List<FundamentalMatrix> fundamentalMatrices);
}
