/*
 * Copyright (C) 2015 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.irurueta.ar.epipolar;

/**
 * Interface to handle events generated by Corrector instances.
 */
public interface CorrectorListener {
    
    /**
     * Called when correction of points starts.
     * @param corrector instance that generated the event.
     */
    void onCorrectStart(Corrector corrector);
    
    /**
     * Called when correction of points finishes.
     * @param corrector instance that generated the event.
     */
    void onCorrectEnd(Corrector corrector);
    
    /**
     * Called when progress of correction of points changes significantly.
     * @param corrector instance that generated the event.
     * @param progress progress expressed as a value between 0 and 1.
     */
    void onCorrectProgressChange(Corrector corrector, float progress);
}
