/*
 * Copyright (C) 2017 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.irurueta.ar.sfm;

/**
 * Listener to be notified of events generated by a planar best fundamental 
 * matrix estimator and reconstructor.
 */
public interface PlanarBestFundamentalMatrixEstimatorAndReconstructorListener {
    
    /**
     * Called when estimation starts.
     * @param estimatorAndReconstructor a planar best fundamental matrix 
     * estimator and reconstructor.
     */
    void onEstimateStart(PlanarBestFundamentalMatrixEstimatorAndReconstructor 
            estimatorAndReconstructor);
    
    /**
     * Called when estimation ends.
     * @param estimatorAndReconstructor a planar best fundamental matrix 
     * estimator and reconstructor.
     */
    void onEstimateEnd(PlanarBestFundamentalMatrixEstimatorAndReconstructor 
            estimatorAndReconstructor);
}
