/**
 * @file
 * This file contains implementation of
 * com.irurueta.geometry.sfm.PlanarBestFundamentalMAtrixEstimatorAndReconstructorListener
 * 
 * @author Alberto Irurueta (alberto@irurueta.com)
 * @date May 30, 2017.
 */
package com.irurueta.geometry.sfm;

/**
 * Listener to be notified of events generated by a planar best fundamental 
 * matrix estimator and reconstructor.
 */
public interface PlanarBestFundamentalMatrixEstimatorAndReconstructorListener {
    
    /**
     * Called when estimation starts.
     * @param estimatorAndReconstructor a planar best fundamental matrix 
     * estimator and reconstructor.
     */
    void onEstimateStart(PlanarBestFundamentalMatrixEstimatorAndReconstructor 
            estimatorAndReconstructor);
    
    /**
     * Called when estimation ends.
     * @param estimatorAndReconstructor a planar best fundamental matrix 
     * estimator and reconstructor.
     */
    void onEstimateEnd(PlanarBestFundamentalMatrixEstimatorAndReconstructor 
            estimatorAndReconstructor);
}
