/**
 * @file
 * This file contains implementation of
 * com.irurueta.geometry.sfm.SinglePoint3DTriangulatorListener
 * 
 * @author Alberto Irurueta (alberto@irurueta.com)
 * @date April 29, 2015
 */
package com.irurueta.geometry.sfm;

/**
 * Handles events generated by a SinglePoint3DTriangulator
 */
public interface SinglePoint3DTriangulatorListener {
    
    /**
     * Called when triangulation starts
     * @param triangulator a triangulator generating the event
     */
    public void onTriangulateStart(SinglePoint3DTriangulator triangulator);
    
    /**
     * Called when triangulation ends
     * @param triangulator a triangulator generating the event
     */
    public void onTriangulateEnd(SinglePoint3DTriangulator triangulator);
}
